import { ArrowRight, BarChart3, Check, ChevronRight, ClipboardCheck, FileCheck2, GraduationCap, Mail, MapPin, Phone, RadioTower, Route, ShieldCheck, Users } from 'lucide-react';

const capabilities = [
  { icon: ClipboardCheck, label: 'Operations Management', copy: 'Build a repeatable operating rhythm across sites, crews and handoffs.', bullets:['Daily operating cadence','Site readiness & closeout','Roles, SOPs and escalation paths'] },
  { icon: BarChart3, label: 'Data & Reporting', copy: 'Turn field updates into decisions without adding more administrative drag.', bullets:['Operational KPI design','Dashboards and scorecards','Reporting workflow cleanup'] },
  { icon: GraduationCap, label: 'Instructional Design', copy: 'Help technicians and supervisors perform the work the same way, every time.', bullets:['Onboarding systems','Job aids and field guides','Supervisor enablement'] },
];

const packages = [
  { name:'Field Ops Diagnostic', price:'$1,500', note:'starting at', time:'1–2 weeks', featured:false, items:['Stakeholder and workflow review','Field-to-office friction map','Top 3 operational priorities','30-day action plan'] },
  { name:'Operations Control Sprint', price:'$4,800', note:'starting at', time:'4–6 weeks', featured:true, items:['Operating cadence and ownership','Site readiness + closeout flow','Core KPI scorecard','SOP and action toolkit'] },
  { name:'Ongoing Ops Support', price:'$3,200', note:'starting monthly', time:'Flexible', featured:false, items:['Weekly operating review','KPI and exception tracking','Process improvement support','Supervisor coaching'] },
];

const schema = { '@context':'https://schema.org', '@type':'ProfessionalService', name:'Corea Operations Group LLC', alternateName:'COREA OPS', description:'Field operations and performance consulting for telecom, fiber and technical field service teams.', areaServed:['Indiana','United States'], telephone:'+1-502-649-4699', email:'coreamenamarcos@gmail.com', address:{'@type':'PostalAddress',addressRegion:'IN',addressCountry:'US'}, serviceType:['Field Operations Management','Performance Improvement','Data Reporting','Instructional Design'] };

export default function Home() {
  return <main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}} />
    <header className="site-header"><a className="brand" href="#top" aria-label="Corea Ops home">COREA<span>OPS</span><i /></a><nav aria-label="Primary navigation"><a href="#solutions">Solutions</a><a href="#packages">Packages</a><a href="#process">How it works</a><a href="#contact">Contact</a></nav><a className="header-cta" href="tel:+15026494699"><Phone size={16}/><span>(502) 649-4699</span></a></header>

    <section id="top" className="hero"><div className="hero-grid" aria-hidden="true"/><div className="hero-glow" aria-hidden="true"/>
      <div className="hero-content"><p className="eyebrow"><MapPin size={15}/> Indiana-based · Serving U.S. field operations</p><h1>Turn field activity into <em>operational control.</em></h1><p className="hero-copy">Corea Ops helps telecom, fiber and technical service teams organize field execution, see the right data and train people to deliver consistently.</p><div className="hero-actions"><a className="button button-primary" href="#contact">Book a 20-minute call <ArrowRight size={18}/></a><a className="button button-secondary" href="#solutions">Explore solutions</a></div><ul className="trust-line" aria-label="Corea Ops approach"><li>Built for the field</li><li>Clear deliverables</li><li>Practical execution</li></ul></div>
      <aside className="ops-panel" aria-label="Field operations control preview"><div className="panel-top"><span>FIELD CONTROL</span><b>LIVE VIEW</b></div><div className="metric"><small>Today&apos;s focus</small><strong>Keep every site moving.</strong></div><div className="status-row"><span><i className="green"/> Site readiness</span><b>On track</b></div><div className="status-row"><span><i className="orange"/> Crew handoffs</span><b>2 actions</b></div><div className="status-row"><span><i className="blue"/> Closeout quality</span><b>Visible</b></div><div className="panel-note">One operating rhythm. Fewer blind spots.</div></aside>
    </section>

    <section className="problem-band"><div><span>THE FIELD DOESN&apos;T WAIT</span><h2>Growth exposes every gap in the operation.</h2></div><p>Missing handoffs, scattered updates, unclear ownership and inconsistent training cost time long before they appear on a report. Corea Ops connects the people, process and information behind the work.</p></section>

    <section id="solutions" className="solutions-section section-pad"><div className="section-heading"><p className="kicker">Connected capabilities</p><h2>One operating system for better field execution.</h2><p>Start with the pressure point you feel today. We design each engagement to work with your current team and tools.</p></div><div className="solution-grid">{capabilities.map(({icon:Icon,label,copy,bullets},index)=><article key={label}><div className="solution-top"><span>0{index+1}</span><Icon/></div><h3>{label}</h3><p>{copy}</p><ul>{bullets.map(item=><li key={item}><Check size={14}/>{item}</li>)}</ul></article>)}</div></section>

    <section className="field-focus"><div className="field-visual"><div className="signal signal-a"><RadioTower/><span>FIELD</span></div><div className="signal signal-b"><Users/><span>CREWS</span></div><div className="signal signal-c"><FileCheck2/><span>CLOSEOUT</span></div><div className="signal-center"><b>OPS</b><small>FIELD<br/>OPERATIONS<br/>PERFORMANCE</small></div></div><div className="field-copy"><p className="kicker light">Priority vertical</p><h2>Built around the realities of fiber, telecom and technical field services.</h2><p>We understand that the best process is the one supervisors and technicians can actually run between dispatch, site access, installation, quality checks and closeout.</p><div className="focus-list"><span><ShieldCheck/>Site readiness</span><span><Route/>Crew coordination</span><span><FileCheck2/>Closeout discipline</span><span><BarChart3/>Operational visibility</span></div></div></section>

    <section id="packages" className="packages section-pad"><div className="section-heading compact"><p className="kicker">Simple starting points</p><h2>Clear scope. Useful output. No vague consulting.</h2><p>Prices are starting points in U.S. dollars. Final scope and travel, if needed, are confirmed before work begins.</p></div><div className="package-grid">{packages.map(pkg=><article className={pkg.featured?'featured':''} key={pkg.name}>{pkg.featured&&<div className="popular">MOST PRACTICAL START</div>}<p className="package-time">{pkg.time}</p><h3>{pkg.name}</h3><div className="price"><small>{pkg.note}</small><strong>{pkg.price}</strong></div><ul>{pkg.items.map(item=><li key={item}><Check size={15}/>{item}</li>)}</ul><a href="#contact">Discuss this package <ChevronRight size={16}/></a></article>)}</div><div className="addons"><b>Also available as focused projects:</b><span>Data dashboard setup from $2,400</span><span>Training or SOP build from $2,900</span></div></section>

    <section id="process" className="process section-pad"><div className="section-heading compact"><p className="kicker">How we work</p><h2>From field reality to a system your team can run.</h2></div><ol><li><b>01</b><div><h3>Listen in context</h3><p>We learn the work, the constraints and what leadership needs to see.</p></div></li><li><b>02</b><div><h3>Make the gaps visible</h3><p>We map handoffs, ownership, information and recurring exceptions.</p></div></li><li><b>03</b><div><h3>Build the practical system</h3><p>We create the cadence, tools, scorecards and learning support.</p></div></li><li><b>04</b><div><h3>Enable the team</h3><p>We help supervisors and staff adopt, use and improve the new rhythm.</p></div></li></ol></section>

    <section className="contact-person"><div><p className="kicker light">Your U.S. field contact</p><h2>Field experience at the first conversation.</h2><p>Marcos Corea leads Corea Ops Group&apos;s commercial and operational development in the United States. His background spans technician work, field supervision and site logistics management—so the conversation starts with how work actually happens.</p><div className="role-tags"><span>Technician</span><span>Field supervisor</span><span>Site logistics</span></div></div><aside><span>CONTACT</span><h3>Marcos Corea</h3><p>U.S. Field Operations Contact</p><a href="tel:+15026494699"><Phone/>+1 (502) 649-4699</a><a href="mailto:coreamenamarcos@gmail.com?subject=COREA%20OPS%20-%20Field%20Operations%20Conversation"><Mail/>coreamenamarcos@gmail.com</a></aside></section>

    <section id="contact" className="contact-section"><div><p className="kicker light">Start with the operation</p><h2>What is slowing the field down?</h2><p>Bring one operational challenge to a focused 20-minute call. We&apos;ll determine whether Corea Ops can help and identify the most useful next step.</p></div><div className="contact-actions"><a className="button button-primary" href="tel:+15026494699"><Phone size={18}/> Call (502) 649-4699</a><a className="button button-white" href="mailto:coreamenamarcos@gmail.com?subject=COREA%20OPS%20-%20Field%20Operations%20Conversation"><Mail size={18}/> Email Corea Ops</a><small>Monday–Friday · Eastern Time · Remote and on-site engagements</small></div></section>

    <footer><a className="brand" href="#top">COREA<span>OPS</span><i/></a><p>Field operations and performance consulting for U.S. service teams.</p><div><span>Indiana, USA</span><a href="tel:+15026494699">+1 (502) 649-4699</a><a href="mailto:coreamenamarcos@gmail.com">coreamenamarcos@gmail.com</a></div><small>© 2026 Corea Operations Group LLC. Pricing shown is in USD and subject to confirmed scope.</small></footer>
  </main>;
}
